import styled from 'styled-components'

export const LoaderStyled = styled.div`
  position: absolute;
  top: 40vh;
  display: flex;
  justify-content: center;
  align-items: center;
  @keyframes ldio-j23wxhxd7h {
    0% {
      top: 123.30000000000001px;
      left: 123.30000000000001px;
      width: 0;
      height: 0;
      opacity: 1;
    }
    100% {
      top: 1.37px;
      left: 1.37px;
      width: 243.86px;
      height: 243.86px;
      opacity: 0;
    }
  }
  .ldio-j23wxhxd7h div {
    position: absolute;
    border-width: 13.700000000000001px;
    border-style: solid;
    opacity: 1;
    border-radius: 50%;
    animation: ldio-j23wxhxd7h 1.1764705882352942s cubic-bezier(0, 0.2, 0.8, 1)
      infinite;
  }
  .ldio-j23wxhxd7h div:nth-child(1) {
    border-color: #353535;
    animation-delay: 0s;
  }
  .ldio-j23wxhxd7h div:nth-child(2) {
    border-color: #666666;
    animation-delay: -0.5882352941176471s;
  }
  .loadingio-spinner-ripple-x95y7ykef7n {
    width: 274px;
    height: 274px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-j23wxhxd7h {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-j23wxhxd7h div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`
