import styled from 'styled-components'

export const LoaderStyled = styled.div`
  position: absolute;
  top: 40vh;
  display: flex;
  justify-content: center;
  align-items: center;
  @keyframes ldio-1pgasvxlpp8 {
    0% {
      background: #d8dddf;
    }
    12.5% {
      background: #d8dddf;
    }
    12.625% {
      background: #a3a3ac;
    }
    100% {
      background: #a3a3ac;
    }
  }
  .ldio-1pgasvxlpp8 div {
    position: absolute;
    width: 62.08px;
    height: 62.08px;
    background: #a3a3ac;
    animation: ldio-1pgasvxlpp8 0.5434782608695652s linear infinite;
  }
  .loadingio-spinner-blocks-fc2p5p6mi34 {
    width: 194px;
    height: 194px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-1pgasvxlpp8 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-1pgasvxlpp8 div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`
